# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-14 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=10000, null=True)),
                ('imagen', models.FileField(upload_to='static')),
                ('color', models.CharField(blank=True, max_length=1000, null=True)),
                ('relink', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, db_column='destino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'distrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'empleo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favoritoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favoritoproducto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('datocategoria', models.ForeignKey(blank=True, db_column='datocategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Categoria')),
            ],
            options={
                'db_table': 'marketing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'modelo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True, null=True)),
                ('p256dh', models.TextField(blank=True, null=True)),
                ('auth', models.TextField(blank=True, null=True)),
                ('endpoint', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='static')),
            ],
            options={
                'db_table': 'photo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(blank=True, db_column='photo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Photo')),
            ],
            options={
                'db_table': 'photoproducto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=1000, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('anio', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometraje', models.CharField(blank=True, max_length=1000, null=True)),
                ('cilindros', models.CharField(blank=True, max_length=1000, null=True)),
                ('transmision', models.CharField(blank=True, max_length=100, null=True)),
                ('combustible', models.CharField(blank=True, max_length=1000, null=True)),
                ('condicion', models.CharField(blank=True, max_length=1000, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1000, null=True)),
                ('transaction', models.CharField(blank=True, max_length=1000, null=True)),
                ('telefono', models.CharField(blank=True, max_length=1000, null=True)),
                ('animal', models.IntegerField(blank=True, null=True)),
                ('metros2', models.CharField(blank=True, max_length=1000, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('salarioestimado', models.CharField(blank=True, max_length=10000, null=True)),
                ('detalleservicio', models.CharField(blank=True, max_length=1000, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banios', models.IntegerField(blank=True, db_column='banios', null=True)),
                ('piscina', models.IntegerField(blank=True, null=True)),
                ('jardin', models.IntegerField(blank=True, null=True)),
                ('amueblado', models.IntegerField(blank=True, null=True)),
                ('gimnasio', models.IntegerField(blank=True, null=True)),
                ('sauna', models.IntegerField(blank=True, null=True)),
                ('jacuzzi', models.IntegerField(blank=True, null=True)),
                ('ambientes', models.IntegerField(blank=True, null=True)),
                ('antiguedad', models.CharField(blank=True, max_length=1000, null=True)),
                ('auto', models.ForeignKey(blank=True, db_column='auto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Auto')),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Categoria')),
                ('color', models.ForeignKey(blank=True, db_column='color', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Color')),
                ('curso', models.ForeignKey(blank=True, db_column='curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cursos')),
                ('distrito', models.ForeignKey(blank=True, db_column='distrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Distrito')),
                ('empleo', models.ForeignKey(blank=True, db_column='empleo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Empleo')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=110, null=True)),
            ],
            options={
                'db_table': 'provincia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=10000, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='static')),
                ('check_imagen', models.BooleanField(default=0, max_length=100)),
                ('activo', models.ForeignKey(blank=True, db_column='activo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Categoria')),
            ],
            options={
                'db_table': 'subcategoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='static')),
            ],
            options={
                'db_table': 'video',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Videoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(blank=True, db_column='producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producto')),
                ('video', models.ForeignKey(blank=True, db_column='video', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Video')),
            ],
            options={
                'db_table': 'videoproducto',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='provincia',
            field=models.ForeignKey(blank=True, db_column='provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Provincia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='servicio',
            field=models.ForeignKey(blank=True, db_column='servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Servicios'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, db_column='subcategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='subcategoria',
            field=models.ForeignKey(blank=True, db_column='subcategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subcategoria'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritoproducto',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='favoritoproducto',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(blank=True, db_column='provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Provincia'),
        ),
        migrations.AddField(
            model_name='chat',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Marca'),
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Modelo'),
        ),
        migrations.AddField(
            model_name='auto',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Tipo'),
        ),
    ]
