# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-14 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180414_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='static'),
        ),
    ]
