# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180414_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Slug')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('iid', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scrap',
                'db_table': 'scrap',
                'managed': True,
            },
        ),
    ]
