# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='telefono',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
