# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_producto_id_olx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
