# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180415_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoproducto',
            name='photo_olx',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
