# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180415_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
