# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180415_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='user_olx',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
