# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_producto_user_olx'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='relink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Primera imagen de portada?'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='check_imagen',
            field=models.BooleanField(default=0, max_length=100, verbose_name='Imagen para portada?'),
        ),
    ]
