# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180422_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datodepagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=110, null=True)),
                ('direccion', models.CharField(blank=True, max_length=110, null=True)),
                ('icono', models.FileField(blank=True, null=True, upload_to='static')),
                ('lema', models.CharField(blank=True, max_length=110, null=True)),
                ('telefono', models.CharField(blank=True, max_length=110, null=True)),
            ],
            options={
                'db_table': 'datodepagina',
                'managed': True,
            },
        ),
    ]
