# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_datodepagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='datodepagina',
            name='descripcion_tienda',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
