# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_datodepagina_descripcion_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='datodepagina',
            name='imagen_tienda',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
